### ISSUE TITLE
Avaliação do projeto inicial

### ISSUE THREAD

**Issue by santos-fernando** [ipdmartins/DistributedChat-projeto#1]
EQUIPE		NOTA: 1.2 (nota máxima da etapa: 1.5)
	Igor Martins
	
ALOCAÇÃO DAS TAREFAS
Ok, a equipe tem apenas um aluno.

DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR
Na mensagem "register", seria importante descrever quais são os dados que serão enviados; idem para as mensagens "actualizeRegister", e "addContact", e "removeContact", e "notifyLive"

DIAGRAMA DE CLASSE SERVIDOR
Na classe ClienteServer, não será necessário armazenar o IP, além da porta?
Uma sugestão para o servidor é adotar o padrão Strategy ou Command para tratar as mensagens.

DIAGRAMA DE SEQUÊNCIA PRELIMINAR CLIENTE/CLIENTE
Não estão especificados quais são os dados enviados para o cliente nas mensagens "message" e "file". Os dados do arquivo serão enviados de uma só vez? ou haverá um laço de repetição para enviar em blocos? 

OBSERVAÇÕES
Referente ao protótipo da tela: Não ficou claro qual a diferença entre o painel da esquerda ("users") e o da direita ("my contacts"). A sugestão é utilizar apenas um painel que mostra os contatos. Se quiser complementar o protótipo da tela, poderia colocar também como vai ser o envio do arquivo. 
O acadêmico pode realizar os ajustes solicitados e fazer push até 11/11 ao meio-dia para melhorar a nota desta etapa.

**Comment by ipdmartins** [comment]
DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR: Corrigido. Somente o método actualizeRegister foi excluído, pois o método register também vai exercer esse papel.

DIAGRAMA DE CLASSE SERVIDOR: corrigido.

DIAGRAMA DE SEQUÊNCIA PRELIMINAR CLIENTE/CLIENTE: corrigido.

OBSERVAÇÕES: corrigido.

**Comment by santos-fernando** [comment]
EQUIPE		NOTA FINAL: 1.5 (nota máxima da etapa: 1.5)
	Igor Martins
	
DIAGRAMA DE SEQUÊNCIA DEFINITIVO PROTOCOLO CLIENTE/SERVIDOR
**[Revisão de 2019-11-11]** Ok.

DIAGRAMA DE CLASSE SERVIDOR
**[Revisão de 2019-11-11]** Ok.

DIAGRAMA DE SEQUÊNCIA PRELIMINAR CLIENTE/CLIENTE
**[Revisão de 2019-11-11]** Ok para esta etapa, mas ainda fica a questão se o arquivo será enviado de uma só vez ou em blocos (quando for estudar sobre o envio de arquivos, vc verá que é necessário adotar esta última estratégia - em blocos).

OBSERVAÇÕES
**[Revisão de 2019-11-11]** Ok.
